### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [teads/teads-analytics-gtm-template#2]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) The documentation [url](https://support.teads.tv/support/solutions/articles/36000313709-teads-analytics-tag-for-publishers) mentioned in the metadata file is behing a login screen. Please provide a valid url.
![Screenshot 2021-09-28 1 28 24 PM](https://user-images.githubusercontent.com/53495700/135161099-d6659fde-d989-4f5d-9cfb-0a5acd75bee8.png)

**Comment by github-xavier-bucchiotty** [comment]
Thanks for reaching @praveena-pappu .

We opened the documentation. I'll be happy to continue the review with you.

**Comment by github-xavier-bucchiotty** [comment]
Thanks again for all your reviews @praveena-pappu . 

Can I help you for the review and get this new template approved please ?
Do you want to close this issue to open next a new one ?

**Comment by github-xavier-bucchiotty** [comment]
Hi @praveena-pappu , would it be possible to have some news.
Is there any way I can help you here ?
